### ISSUE TITLE
Julia run

### ISSUE THREAD

**Issue by teuffy** [GTrunSec/Jupyter-data-science-environment#1]
Hi

I got the error message when starting a julia kernel within jupyter
"https://github.com/GTrunSec/Jupyter-data-science-environment

"could not open file /home/me/Jupyter-ds-env/.julia_pkgs/packages/IJulia/tON8L/src/kernel.jl"

could it be related to the julia version (1.5 installed) where I have "/.julia.pkgs/packages/IJulia/rWZ9e/src/kernel.jl" ?

Cheers

**Comment by GTrunSec** [comment]
Fixed by bf02d007eccb7088aa5da6e7d74cd327e8c5e200 thanks for your reporting.
